// Stacked-notes renderer.
// URL ?n=home,manifesto,project-democraicy — left-to-right stack of notes.
// Click a link inside a note: append it to the stack (and prune notes to the right).
// Click the close button: pop that note + everything after it.
// Tap a tab in the header to reset to that single note.
//
// Two content sources, in this order:
//   1. window.NOTES (notes.js) for richly structured pages (home, indexes, manifesto).
//   2. content/<id>.md  (fetched at runtime) for editorial content. Drop a .md file
//      in content/ with the right slug and it appears. See README.md for details.

(function () {
  const NOTES = window.NOTES;
  const NOTE_CACHE = new Map();   // id -> note (resolved markdown notes)
  const PENDING = new Map();      // id -> Promise (avoid double-fetch)
  const MISSING = new Set();      // id -> tried and not found
  // Auto-index: list of every .md note in content/, keyed by slug.
  // Populated lazily on the first auto-list render. Generated by regen.py.
  let AUTO_INDEX = null;
  let AUTO_INDEX_PROMISE = null;
  function loadAutoIndex() {
    if (AUTO_INDEX) return Promise.resolve(AUTO_INDEX);
    if (AUTO_INDEX_PROMISE) return AUTO_INDEX_PROMISE;
    AUTO_INDEX_PROMISE = fetch('content/_index.json', { cache: 'no-cache' })
      .then(r => r.ok ? r.json() : Promise.reject(new Error('no _index.json')))
      .then(json => { AUTO_INDEX = Array.isArray(json) ? json : []; return AUTO_INDEX; })
      .catch(err => {
        console.warn('[uzd] auto-index unavailable:', err && err.message || err,
          '— run `python3 regen.py` and refresh.');
        AUTO_INDEX = [];
        return AUTO_INDEX;
      });
    return AUTO_INDEX_PROMISE;
  }

  const $stackInner = document.querySelector('.stack-inner');
  const $stack = document.querySelector('.stack');
  const $chromeNav = document.querySelector('.chrome-nav');
  const $mobileMenuToggle = document.querySelector('.mobile-menu-toggle');
  const $mobileMenu = document.querySelector('.mobile-menu');

  const PRIMARY_TABS = [
    { id: 'who-we-are', label: 'who we are', icon: 'people' },
    { id: 'fundamentals', label: 'fundamentals', icon: 'document' },
    { id: 'projects', label: 'projects', icon: 'folder' },
    { id: 'team', label: 'team', icon: 'person' },
    { id: 'partners', label: 'partners', icon: 'planet' },
  ];

  // Old hub URLs and section paths still resolve. ?n=manifesto and
  // /manifesto continue to work as redirects to the renamed slug.
  const SLUG_ALIASES = {
    manifesto: 'fundamentals',
  };
  function resolveSlug(slug) {
    return SLUG_ALIASES[slug] || slug;
  }

  const SOLAR_DUOTONE = {
    home: '<path fill="currentColor" opacity=".5" d="M2 12.204c0-2.289 0-3.433.52-4.381c.518-.949 1.467-1.537 3.364-2.715l2-1.241C9.889 2.622 10.892 2 12 2s2.11.622 4.116 1.867l2 1.241c1.897 1.178 2.846 1.766 3.365 2.715S22 9.915 22 12.203v1.522c0 3.9 0 5.851-1.172 7.063S17.771 22 14 22h-4c-3.771 0-5.657 0-6.828-1.212S2 17.626 2 13.725z"/><path fill="currentColor" d="M11.25 18a.75.75 0 0 0 1.5 0v-3a.75.75 0 0 0-1.5 0z"/>',
    people: '<circle cx="15" cy="6" r="3" fill="currentColor" opacity=".4"/><ellipse cx="16" cy="17" fill="currentColor" opacity=".4" rx="5" ry="3"/><circle cx="9.001" cy="6" r="4" fill="currentColor"/><ellipse cx="9.001" cy="17.001" fill="currentColor" rx="7" ry="4"/>',
    document: '<path fill="currentColor" opacity=".5" d="M3 10c0-3.771 0-5.657 1.172-6.828S7.229 2 11 2h2c3.771 0 5.657 0 6.828 1.172S21 6.229 21 10v4c0 3.771 0 5.657-1.172 6.828S16.771 22 13 22h-2c-3.771 0-5.657 0-6.828-1.172S3 17.771 3 14z"/><path fill="currentColor" fill-rule="evenodd" d="M7.25 12a.75.75 0 0 1 .75-.75h8a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1-.75-.75m0-4A.75.75 0 0 1 8 7.25h8a.75.75 0 0 1 0 1.5H8A.75.75 0 0 1 7.25 8m0 8a.75.75 0 0 1 .75-.75h5a.75.75 0 0 1 0 1.5H8a.75.75 0 0 1-.75-.75" clip-rule="evenodd"/>',
    folder: '<path fill="currentColor" opacity=".5" d="M2 6.95c0-.883 0-1.324.07-1.692A4 4 0 0 1 5.257 2.07C5.626 2 6.068 2 6.95 2c.386 0 .58 0 .766.017a4 4 0 0 1 2.18.904c.144.119.28.255.554.529L11 4c.816.816 1.224 1.224 1.712 1.495a4 4 0 0 0 .848.352C14.098 6 14.675 6 15.828 6h.374c2.632 0 3.949 0 4.804.77q.119.105.224.224c.77.855.77 2.172.77 4.804V14c0 3.771 0 5.657-1.172 6.828S17.771 22 14 22h-4c-3.771 0-5.657 0-6.828-1.172S2 17.771 2 14z"/><path fill="currentColor" d="M20 6.238c0-.298-.005-.475-.025-.63a3 3 0 0 0-2.583-2.582C17.197 3 16.965 3 16.5 3H9.988c.116.104.247.234.462.45L11 4c.816.816 1.224 1.224 1.712 1.495a4 4 0 0 0 .849.352C14.098 6 14.675 6 15.829 6h.373c1.78 0 2.957 0 3.798.238"/><path fill="currentColor" fill-rule="evenodd" d="M12.25 10a.75.75 0 0 1 .75-.75h5a.75.75 0 0 1 0 1.5h-5a.75.75 0 0 1-.75-.75" clip-rule="evenodd"/>',
    person: '<circle cx="12" cy="6" r="4" fill="currentColor"/><ellipse cx="12" cy="17" fill="currentColor" opacity=".5" rx="7" ry="4"/>',
    planet: '<path fill="currentColor" opacity=".5" d="M20 12a8 8 0 1 1-16 0a8 8 0 0 1 16 0"/><path fill="currentColor" d="M19.009 6.784a.75.75 0 0 0-.138-1.494q-.637.06-1.345.2a.75.75 0 0 0-.472.309l1.117 1.097q.444-.075.838-.112"/><path fill="currentColor" fill-rule="evenodd" d="M20.937 5.38a.75.75 0 1 0-.346 1.459c.394.093.546.232.602.322c.063.102.133.366-.157.948a.75.75 0 0 0 1.343.67c.378-.759.563-1.65.086-2.413c-.344-.55-.923-.843-1.528-.987m-.225 5.581a.75.75 0 1 0-1.065-1.057c-.686.692-1.567 1.43-2.608 2.171a.75.75 0 0 0 .87 1.222c1.095-.78 2.044-1.572 2.803-2.336M3.587 14.947q.302-.378.706-.79l-.238-1.33a.75.75 0 0 0-.744.189q-.503.505-.896.995a.75.75 0 1 0 1.172.937m12.163-.243a.75.75 0 1 0-.77-1.287a35 35 0 0 1-3.092 1.645a.75.75 0 0 0 .638 1.357a37 37 0 0 0 3.224-1.715M2.815 16.25a.75.75 0 0 0-1.43-.455c-.191.601-.211 1.262.15 1.84c.453.724 1.307 1.006 2.154 1.087a.75.75 0 1 0 .143-1.493c-.694-.066-.948-.267-1.025-.39c-.05-.08-.102-.244.008-.589m7.268 1.203a.75.75 0 0 0-.527-1.404c-1.225.46-2.365.791-3.362.989a.75.75 0 0 0 .291 1.471c1.093-.216 2.313-.574 3.598-1.056" clip-rule="evenodd"/>',
    letter: '<path fill="currentColor" opacity=".5" d="M14.2 3H9.8C5.652 3 3.577 3 2.289 4.318S1 7.758 1 12s0 6.364 1.289 7.682S5.652 21 9.8 21h4.4c4.148 0 6.223 0 7.511-1.318S23 16.242 23 12s0-6.364-1.289-7.682S18.348 3 14.2 3"/><path fill="currentColor" d="M19.128 8.033a.825.825 0 0 0-1.056-1.268l-2.375 1.98c-1.026.855-1.738 1.447-2.34 1.833c-.582.375-.977.5-1.357.5s-.774-.125-1.357-.5c-.601-.386-1.314-.978-2.34-1.834L5.928 6.765a.825.825 0 0 0-1.056 1.268l2.416 2.014c.975.812 1.765 1.47 2.463 1.92c.726.466 1.434.762 2.25.762c.814 0 1.522-.296 2.249-.763c.697-.448 1.487-1.107 2.462-1.92z"/>',
  };

  function getStackFromUrl() {
    const params = new URLSearchParams(location.search);
    const raw = (params.get('n') || 'home').split(',').filter(Boolean);
    const stack = raw.length ? raw : ['home'];
    // Active column is the last by default; ?a=N (0-based) overrides.
    let activeIndex = stack.length - 1;
    const aRaw = params.get('a');
    if (aRaw !== null) {
      const n = parseInt(aRaw, 10);
      if (!isNaN(n) && n >= 0 && n < stack.length) activeIndex = n;
    }
    return { stack, activeIndex };
  }

  function arraysEqual(a, b) {
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
    return true;
  }

  // Simple filter for the auto-list block. The filter is an object like
  // { type: 'project', role: ['lead','partner'] }. A note matches if every
  // key's value matches (string equality, or membership when the filter
  // value is an array).
  function matchesFilter(note, filter) {
    for (const k of Object.keys(filter)) {
      const want = filter[k];
      const got = note[k];
      if (Array.isArray(want)) {
        if (!want.includes(got)) return false;
      } else if (got !== want) {
        return false;
      }
    }
    return true;
  }

  // On mobile, the active note always sits at the top of the body. After any
  // change of active column, scroll the page back to the top so the user
  // lands at the start of the freshly-opened note instead of wherever they
  // happened to be scrolled within the previous one.
  function scrollActiveIntoViewOnMobile() {
    if (window.matchMedia && window.matchMedia('(max-width: 720px)').matches) {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  }

  function setStackUrl(ids, activeIndex, mode) {
    const params = new URLSearchParams(location.search);
    if (ids.length === 1 && ids[0] === 'home') {
      params.delete('n');
    } else {
      params.set('n', ids.join(','));
    }
    // Only encode the active index when it's not the default (the last column).
    if (typeof activeIndex === 'number' && activeIndex !== ids.length - 1) {
      params.set('a', String(activeIndex));
    } else {
      params.delete('a');
    }
    const q = params.toString();
    const url = q ? `?${q}` : location.pathname;
    // Skip the write if the URL is already correct (avoids dummy entries
    // when async re-renders fire after the user has already pushed state).
    const current = location.pathname + (location.search || '');
    if (current === url) return;
    if (mode === 'replace') history.replaceState({ stack: ids.slice(), activeIndex }, '', url);
    else history.pushState({ stack: ids.slice(), activeIndex }, '', url);
  }

  // ---------- markdown loader ----------

  function getNote(id) {
    id = resolveSlug(id);
    return NOTES[id] || NOTE_CACHE.get(id) || null;
  }

  function loadNote(id) {
    id = resolveSlug(id);
    if (NOTES[id]) return Promise.resolve(NOTES[id]);
    if (NOTE_CACHE.has(id)) return Promise.resolve(NOTE_CACHE.get(id));
    if (MISSING.has(id)) return Promise.resolve(null);
    if (PENDING.has(id)) return PENDING.get(id);
    const url = `content/${id}.md`;
    const p = fetch(url, { cache: 'no-cache' })
      .then(r => r.ok ? r.text() : Promise.reject(new Error(`HTTP ${r.status}`)))
      .then(text => {
        const note = parseMdNote(id, text);
        NOTE_CACHE.set(id, note);
        return note;
      })
      .catch(err => {
        // Surface the underlying problem in devtools so the user knows whether
        // the file is missing, the server is misconfigured, or the page was
        // opened via file:// (where fetch is blocked by the browser).
        const isFile = location.protocol === 'file:';
        console.error(
          `[uzd] couldn't load ${url}:`, err && err.message || err,
          isFile ? '(opened via file:// — browsers block fetch; serve over http instead)' : ''
        );
        MISSING.add(id);
        return null;
      })
      .finally(() => PENDING.delete(id));
    PENDING.set(id, p);
    return p;
  }

  function parseMdNote(id, text) {
    let front = {};
    let body = text;
    const fmMatch = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
    if (fmMatch) {
      front = parseFrontMatter(fmMatch[1]);
      body = fmMatch[2];
    }
    const accent = front.accent || (front.type === 'project' ? 'green' : 'indigo');
    const pills = parsePills(front.pills);
    return {
      id,
      type: front.type || 'note',
      kicker: front.kicker || front.type || id,
      title: front.title || id,
      subtitle: front.subtitle || front.tagline || '',
      accent,
      pills,
      images: Array.isArray(front.images) ? front.images.filter(Boolean) : [],
      body: [{ kind: 'md', html: mdToHtml(body) }],
      _md: true,
    };
  }

  function parseFrontMatter(s) {
    const out = {};
    const lines = s.split(/\r?\n/);
    let currentKey = null;
    for (const raw of lines) {
      if (!raw.trim()) { continue; }
      const indented = /^\s+/.test(raw);
      const line = raw.replace(/\r$/, '');
      if (indented && currentKey) {
        const v = line.trim().replace(/^-\s*/, '');
        if (!Array.isArray(out[currentKey])) out[currentKey] = [];
        out[currentKey].push(unquote(v));
        continue;
      }
      const km = line.match(/^([\w-]+):\s*(.*)$/);
      if (!km) continue;
      const k = km[1];
      const v = km[2].trim();
      if (!v) {
        currentKey = k;
        out[k] = [];
      } else if (v.startsWith('[') && v.endsWith(']')) {
        out[k] = v.slice(1, -1).split(',').map(x => unquote(x.trim())).filter(Boolean);
        currentKey = null;
      } else {
        out[k] = unquote(v);
        currentKey = null;
      }
    }
    return out;
  }

  function unquote(s) {
    s = s.trim();
    if (s.length >= 2 && ((s[0] === '"' && s[s.length-1] === '"') || (s[0] === "'" && s[s.length-1] === "'"))) {
      return s.slice(1, -1);
    }
    return s;
  }

  function parsePills(raw) {
    if (!raw) return [];
    const arr = Array.isArray(raw) ? raw : [raw];
    return arr.map(item => {
      const parts = String(item).split('|').map(s => s.trim());
      const out = { label: parts[0] };
      if (parts[1]) out.variant = parts[1];
      return out;
    }).filter(p => p.label);
  }

  function escHtml(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
  function escAttr(s) {
    return escHtml(s).replace(/"/g, '&quot;');
  }

  function parseTableRow(line) {
    // Strip optional leading/trailing pipe and split on | (no escaping needed
    // for our content set; if a cell needs a literal pipe, use &#124;).
    let s = line.trim();
    if (s.startsWith('|')) s = s.slice(1);
    if (s.endsWith('|')) s = s.slice(0, -1);
    return s.split('|').map(c => c.trim());
  }

  function inlineMd(text) {
    // Tokenise inline. Order: escape, code, image, link, bold, italic.
    // We escape the whole string first, then do replacements. Markdown emphasis
    // uses literal * which survives escaping.
    let s = escHtml(text);
    s = s.replace(/`([^`]+)`/g, (_, c) => `<code>${c}</code>`);
    s = s.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, (_, alt, src) =>
      `<img src="${escAttr(src)}" alt="${escAttr(alt)}">`);
    s = s.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, label, href) => {
      const isExternal = /^(?:https?:|mailto:)/.test(href);
      if (isExternal) {
        const tgt = href.startsWith('mailto:') ? '' : ' target="_blank" rel="noopener"';
        return `<a href="${escAttr(href)}"${tgt}>${label}</a>`;
      }
      // Internal: a slug. Strip leading slashes/hashes and any .md suffix,
      // then map /<section>/<slug> → <section-singular>-<slug>, the convention
      // used in content/<prefix>-<slug>.md.
      const path = href.replace(/^[#/]+/, '').replace(/\.md$/, '');
      let noteId;
      if (path.includes('/')) {
        const idx = path.indexOf('/');
        const section = path.slice(0, idx);
        const slug = path.slice(idx + 1);
        const sectionMap = {
          projects: 'project',
          manifesto: 'manifesto',
          team: 'team',
          partners: 'partner',
          curiosities: 'curiosity',
        };
        const prefix = sectionMap[section];
        noteId = prefix ? `${prefix}-${slug}` : slug;
      } else {
        noteId = path;
      }
      return `<a href="?n=${escAttr(noteId)}" data-note="${escAttr(noteId)}">${label}</a>`;
    });
    s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    s = s.replace(/(^|[^*])\*([^*\n]+)\*(?!\*)/g, '$1<em>$2</em>');
    return s;
  }

  function mdToHtml(md) {
    const out = [];
    const lines = md.split(/\r?\n/);
    let i = 0;
    while (i < lines.length) {
      const line = lines[i];
      if (!line.trim()) { i++; continue; }

      // Skip a top-level H1; the title is taken from front matter.
      const h = line.match(/^(#{1,4})\s+(.*?)\s*$/);
      if (h) {
        const lvl = h[1].length;
        if (lvl > 1) out.push(`<h${lvl}>${inlineMd(h[2])}</h${lvl}>`);
        i++;
        continue;
      }

      if (/^-{3,}\s*$/.test(line)) { out.push('<hr>'); i++; continue; }

      if (line.startsWith('>')) {
        const buf = [];
        while (i < lines.length && lines[i].startsWith('>')) {
          buf.push(lines[i].replace(/^>\s?/, ''));
          i++;
        }
        out.push(`<blockquote>${inlineMd(buf.join(' '))}</blockquote>`);
        continue;
      }

      if (/^[-*]\s+/.test(line)) {
        const items = [];
        while (i < lines.length && /^[-*]\s+/.test(lines[i])) {
          items.push(`<li>${inlineMd(lines[i].replace(/^[-*]\s+/, ''))}</li>`);
          i++;
        }
        out.push(`<ul>${items.join('')}</ul>`);
        continue;
      }

      if (/^\d+\.\s+/.test(line)) {
        const items = [];
        while (i < lines.length && /^\d+\.\s+/.test(lines[i])) {
          items.push(`<li>${inlineMd(lines[i].replace(/^\d+\.\s+/, ''))}</li>`);
          i++;
        }
        out.push(`<ol>${items.join('')}</ol>`);
        continue;
      }

      // Image-only paragraph
      const im = line.match(/^!\[([^\]]*)\]\(([^)]+)\)\s*$/);
      if (im) {
        const alt = im[1], src = im[2];
        out.push(`<figure><img src="${escAttr(src)}" alt="${escAttr(alt)}">${alt ? `<figcaption>${escHtml(alt)}</figcaption>` : ''}</figure>`);
        i++;
        continue;
      }

      // GFM-style table: header row, separator row of |---|, then data rows.
      if (line.includes('|') && i + 1 < lines.length) {
        const sep = lines[i + 1];
        if (sep && /\|/.test(sep) && /^[\s|:\-]+$/.test(sep) && /-/.test(sep)) {
          const headers = parseTableRow(line);
          i += 2; // header + separator
          const rows = [];
          while (i < lines.length && lines[i].trim() && lines[i].includes('|')) {
            rows.push(parseTableRow(lines[i]));
            i++;
          }
          const thead = '<thead><tr>' + headers.map(h => `<th>${inlineMd(h)}</th>`).join('') + '</tr></thead>';
          const tbody = '<tbody>' + rows.map(r =>
            '<tr>' + r.map(c => `<td>${inlineMd(c)}</td>`).join('') + '</tr>'
          ).join('') + '</tbody>';
          out.push(`<table>${thead}${tbody}</table>`);
          continue;
        }
      }

      // Raw HTML block: a line beginning with an HTML tag (e.g. <iframe>,
      // <video>, <details>, <div>). We trust the markdown source — the user
      // is the author — and pass these through verbatim until the next blank
      // line. inlineMd is not applied (HTML attributes break the inline
      // tokeniser, and we don't want them mangled).
      if (/^<\s*[a-zA-Z]/.test(line)) {
        const buf = [line];
        i++;
        while (i < lines.length && lines[i].trim() !== '') {
          buf.push(lines[i]);
          i++;
        }
        out.push(buf.join('\n'));
        continue;
      }

      // Paragraph: gather until a blank line or a structural marker.
      const buf = [line];
      i++;
      while (i < lines.length && lines[i].trim() &&
             !/^(#{1,4}\s|>|-{3,}\s*$|[-*]\s|\d+\.\s|!\[|\||<\s*[a-zA-Z])/.test(lines[i])) {
        buf.push(lines[i]);
        i++;
      }
      out.push(`<p>${inlineMd(buf.join(' '))}</p>`);
    }
    // First paragraph becomes the lede.
    for (let j = 0; j < out.length; j++) {
      if (out[j].startsWith('<p>')) {
        out[j] = `<p class="lede">${out[j].slice(3, -4)}</p>`;
        break;
      }
    }
    return out.join('\n');
  }

  // ---------- constellation (partners + projects graph) ----------

  function svgEl(tag, attrs = {}, children = []) {
    const node = document.createElementNS('http://www.w3.org/2000/svg', tag);
    for (const [k, v] of Object.entries(attrs)) {
      if (v == null || v === false) continue;
      node.setAttribute(k, v);
    }
    for (const c of [].concat(children)) {
      if (c == null) continue;
      if (typeof c === 'string') node.appendChild(document.createTextNode(c));
      else node.appendChild(c);
    }
    return node;
  }

  function renderConstellation(ctx) {
    const D = window.UZD_DATA;
    const wrap = el('div', { class: 'b-constellation' });
    if (!D) {
      wrap.appendChild(el('p', { class: 'b-p' }, 'No network data found (assets/data.js).'));
      return wrap;
    }

    // Layout constants. The SVG is responsive: viewBox is fixed, browser scales.
    const W = 760, H = 620;
    const cx = 300, cy = H / 2;
    const ring = 250;

    // Partners on a ring, sorted by # projects desc (largest at top).
    const partners = [...D.partners]
      .sort((a, b) => b.projects.length - a.projects.length)
      .map((p, i, arr) => {
        const angle = (i / arr.length) * Math.PI * 2 - Math.PI / 2;
        return { ...p, x: cx + Math.cos(angle) * ring, y: cy + Math.sin(angle) * ring };
      });

    // Projects: position toward the centroid of their partners; orphans on inner ring.
    const projects = D.projects.map((proj, idx, arr) => {
      let px, py;
      if (proj.partners.length === 0) {
        const a = (idx / arr.length) * Math.PI * 2;
        px = cx + Math.cos(a) * 90;
        py = cy + Math.sin(a) * 90;
      } else {
        const ps = partners.filter(p => proj.partners.includes(p.slug));
        const ax = ps.reduce((s, p) => s + p.x, 0) / ps.length;
        const ay = ps.reduce((s, p) => s + p.y, 0) / ps.length;
        px = cx + (ax - cx) * 0.55;
        py = cy + (ay - cy) * 0.55;
      }
      return { ...proj, x: px, y: py };
    });

    // State held in closure so re-renders don't lose selection.
    let hovered = null;
    let selected = 'ccif';

    const grid = el('div', { class: 'constellation-grid' });
    const svgWrap = el('div', { class: 'constellation-svg' });
    const detail = el('aside', { class: 'constellation-detail' });
    grid.appendChild(svgWrap);
    grid.appendChild(detail);
    wrap.appendChild(grid);

    function focusedSlug() { return hovered || selected; }

    function isHl(kind, slug) {
      const focus = focusedSlug();
      if (!focus) return false;
      const fp = partners.find(p => p.slug === focus);
      const fr = projects.find(p => p.slug === focus);
      if (fp) {
        if (kind === 'partner') return slug === focus;
        if (kind === 'project') return fp.projects.includes(slug);
      }
      if (fr) {
        if (kind === 'project') return slug === focus;
        if (kind === 'partner') return fr.partners.includes(slug);
      }
      return false;
    }

    function paint() {
      svgWrap.innerHTML = '';
      const svg = svgEl('svg', {
        viewBox: `0 0 ${W} ${H}`,
        width: '100%', height: '100%',
        preserveAspectRatio: 'xMidYMid meet',
        role: 'img',
        'aria-label': 'Partner and project network',
      });

      // Dashed ring guideline
      svg.appendChild(svgEl('circle', {
        cx, cy, r: ring,
        fill: 'none', stroke: 'var(--rule)', 'stroke-dasharray': '2 4', opacity: 0.6,
      }));

      const focus = focusedSlug();

      // Edges: uzd -> partners
      partners.forEach(p => {
        const hl = isHl('partner', p.slug);
        svg.appendChild(svgEl('line', {
          x1: cx, y1: cy, x2: p.x, y2: p.y,
          stroke: 'var(--rule)',
          'stroke-width': hl ? 1.5 : 0.5,
          opacity: focus && !hl ? 0.12 : 0.55,
        }));
      });

      // Edges: project -> each of its partners
      projects.forEach(proj => {
        proj.partners.forEach(ps => {
          const partner = partners.find(p => p.slug === ps);
          if (!partner) return;
          const fp = partners.find(p => p.slug === focus);
          const fr = projects.find(p => p.slug === focus);
          const hl =
            (fp && proj.partners.includes(fp.slug) && partner.slug === fp.slug) ||
            (fr && fr.slug === proj.slug);
          svg.appendChild(svgEl('line', {
            x1: proj.x, y1: proj.y, x2: partner.x, y2: partner.y,
            stroke: hl ? 'var(--accent)' : 'var(--rule)',
            'stroke-width': hl ? 1.5 : 0.5,
            opacity: focus && !hl ? 0.08 : 0.5,
          }));
        });
      });

      // uzd center node
      const center = svgEl('g', { class: 'cn-center' });
      center.appendChild(svgEl('circle', { cx, cy, r: 30, fill: 'var(--ink)' }));
      const t = svgEl('text', {
        x: cx, y: cy + 4, 'text-anchor': 'middle', fill: 'var(--bg)',
        'font-family': 'var(--font-display)', 'font-size': 12, 'font-weight': 700,
      });
      t.textContent = 'uzd';
      center.appendChild(t);
      svg.appendChild(center);

      // Project nodes
      projects.forEach(proj => {
        const hl = isHl('project', proj.slug);
        const isFocus = focus === proj.slug;
        const dim = focus && !hl && !isFocus;
        const r = proj.role === 'lead' ? 9 : proj.role === 'partner' ? 7 : 6;
        const fill =
          proj.role === 'lead' ? 'var(--accent)' :
          proj.role === 'partner' ? 'var(--ochre)' : 'var(--green)';
        const g = svgEl('g', { class: 'cn-project', style: 'cursor: pointer;' });
        g.appendChild(svgEl('circle', {
          cx: proj.x, cy: proj.y, r,
          fill,
          stroke: isFocus ? 'var(--ink)' : 'none',
          'stroke-width': 2,
          opacity: dim ? 0.18 : 1,
        }));
        if (hl || isFocus) {
          const lbl = svgEl('text', {
            x: proj.x, y: proj.y - r - 6, 'text-anchor': 'middle',
            fill: 'var(--ink)', 'font-family': 'var(--font-ui)',
            'font-size': 10, 'font-weight': 500,
          });
          lbl.textContent = proj.title;
          g.appendChild(lbl);
        }
        g.addEventListener('mouseenter', () => { hovered = proj.slug; paint(); });
        g.addEventListener('mouseleave', () => { hovered = null; paint(); });
        g.addEventListener('click', () => { selected = proj.slug; paint(); });
        // Double-click → open the corresponding project note in the stack.
        g.addEventListener('dblclick', () => {
          ctx.openNote(`project-${proj.slug}`, ctx.depth);
        });
        svg.appendChild(g);
      });

      // Partner nodes
      partners.forEach(p => {
        const isFocus = focus === p.slug;
        const hl = isHl('partner', p.slug);
        const dim = focus && !isFocus && !hl;
        const r = 16 + Math.min(p.projects.length, 6) * 2;
        const g = svgEl('g', { class: 'cn-partner', style: 'cursor: pointer;' });
        g.appendChild(svgEl('circle', {
          cx: p.x, cy: p.y, r,
          fill: 'var(--bg)',
          stroke: isFocus ? 'var(--accent)' : 'var(--ink)',
          'stroke-width': isFocus ? 2.5 : 1,
          opacity: dim ? 0.3 : 1,
        }));
        const tc = svgEl('text', {
          x: p.x, y: p.y + 4, 'text-anchor': 'middle',
          fill: 'var(--ink)', 'font-family': 'var(--font-ui)',
          'font-size': 10, 'font-weight': 600,
          opacity: dim ? 0.4 : 1,
        });
        tc.textContent = p.country;
        g.appendChild(tc);
        const tn = svgEl('text', {
          x: p.x, y: p.y + r + 14, 'text-anchor': 'middle',
          fill: 'var(--ink-muted)', 'font-family': 'var(--font-display)',
          'font-size': 11, 'font-weight': 500,
          opacity: dim ? 0.4 : 1,
        });
        tn.textContent = p.name;
        g.appendChild(tn);
        g.addEventListener('mouseenter', () => { hovered = p.slug; paint(); });
        g.addEventListener('mouseleave', () => { hovered = null; paint(); });
        g.addEventListener('click', () => { selected = p.slug; paint(); });
        g.addEventListener('dblclick', () => {
          ctx.openNote(`partner-${p.slug}`, ctx.depth);
        });
        svg.appendChild(g);
      });

      svgWrap.appendChild(svg);
      paintDetail();
    }

    function paintDetail() {
      detail.innerHTML = '';
      const focus = focusedSlug();
      const fp = partners.find(p => p.slug === focus);
      const fr = projects.find(p => p.slug === focus);
      if (fp) {
        detail.appendChild(el('div', { class: 'cn-eyebrow' }, `partner · ${D.countryNames[fp.country] || fp.country}`));
        detail.appendChild(el('h3', { class: 'cn-title' }, fp.name));
        detail.appendChild(el('p', { class: 'cn-note' }, fp.note));
        detail.appendChild(el('hr', { class: 'cn-rule' }));
        detail.appendChild(el('div', { class: 'cn-eyebrow' }, `projects together (${fp.projects.length})`));
        const list = el('div', { class: 'cn-list' });
        fp.projects.forEach(slug => {
          const proj = D.projects.find(p => p.slug === slug);
          if (!proj) return;
          const row = el('div', { class: 'cn-list-row' }, [
            el('span', { class: 'cn-list-title' }, proj.title),
            el('span', { class: 'cn-list-year' }, String(proj.year)),
          ]);
          row.addEventListener('click', () => { selected = slug; paint(); });
          row.addEventListener('dblclick', () => ctx.openNote(`project-${slug}`, ctx.depth));
          list.appendChild(row);
        });
        detail.appendChild(list);
        const open = el('button', { class: 'cn-open' }, `read partner note →`);
        open.addEventListener('click', () => ctx.openNote(`partner-${fp.slug}`, ctx.depth));
        detail.appendChild(open);
      } else if (fr) {
        detail.appendChild(el('div', { class: 'cn-eyebrow' }, `project · ${fr.year} · ${fr.role}`));
        detail.appendChild(el('h3', { class: 'cn-title' }, fr.title));
        detail.appendChild(el('p', { class: 'cn-note' }, fr.blurb));
        detail.appendChild(el('hr', { class: 'cn-rule' }));
        detail.appendChild(el('div', { class: 'cn-meta-label' }, 'funder'));
        detail.appendChild(el('div', { class: 'cn-meta-value' }, fr.funderShort));
        detail.appendChild(el('div', { class: 'cn-meta-label' }, 'budget'));
        detail.appendChild(el('div', { class: 'cn-meta-value' }, fr.budget ? `€${fr.budget.toLocaleString('en-US')}` : '—'));
        if (fr.partners && fr.partners.length) {
          detail.appendChild(el('div', { class: 'cn-eyebrow' }, 'partners on this project'));
          fr.partners.forEach(ps => {
            const partner = D.partners.find(p => p.slug === ps);
            if (!partner) return;
            const row = el('div', { class: 'cn-list-row' }, [
              el('span', { class: 'cn-list-title' }, partner.name),
              el('span', { class: 'cn-list-year' }, partner.country),
            ]);
            row.addEventListener('click', () => { selected = ps; paint(); });
            row.addEventListener('dblclick', () => ctx.openNote(`partner-${ps}`, ctx.depth));
            detail.appendChild(row);
          });
        }
        const open = el('button', { class: 'cn-open' }, `read project note →`);
        open.addEventListener('click', () => ctx.openNote(`project-${fr.slug}`, ctx.depth));
        detail.appendChild(open);
      } else {
        detail.appendChild(el('div', { class: 'cn-eyebrow' }, 'hover any node'));
        detail.appendChild(el('p', { class: 'cn-note' },
          'Eleven partners, seventeen projects, six countries. Hover or click any circle for details. Double-click to open the note alongside.'));
      }
    }

    paint();
    return wrap;
  }

  // ---------- block renderers ----------

  function el(tag, attrs = {}, children = []) {
    const node = document.createElement(tag);
    for (const [k, v] of Object.entries(attrs)) {
      if (k === 'class') node.className = v;
      else if (k === 'html') node.innerHTML = v;
      else if (k.startsWith('on')) node.addEventListener(k.slice(2), v);
      else if (v !== undefined && v !== null) node.setAttribute(k, v);
    }
    for (const c of [].concat(children)) {
      if (c == null) continue;
      if (typeof c === 'string') node.appendChild(document.createTextNode(c));
      else node.appendChild(c);
    }
    return node;
  }

  function solarIcon(name) {
    const svg = el('svg', {
      class: 'solar-icon',
      'aria-hidden': 'true',
      viewBox: '0 0 24 24',
      html: SOLAR_DUOTONE[name] || SOLAR_DUOTONE.document,
    });
    svg.setAttribute('focusable', 'false');
    return svg;
  }

  function emphasize(text) {
    // Allow simple *italic* in titles
    const span = document.createElement('span');
    span.innerHTML = String(text).replace(/\*([^*]+)\*/g, '<em>$1</em>');
    return span;
  }

  function renderBlock(b, ctx) {
    switch (b.kind) {
      case 'md': {
        const wrap = el('div', { class: 'b-md', html: b.html });
        // Wire internal links to the stack router.
        wrap.querySelectorAll('a[data-note]').forEach(a => {
          a.addEventListener('click', (e) => {
            e.preventDefault();
            ctx.openNote(a.dataset.note, ctx.depth);
          });
        });
        return wrap;
      }
      case 'constellation': {
        return renderConstellation(ctx);
      }
      case 'auto-list': {
        // Filter the auto-index by `b.filter` (an object whose keys must match
        // each note's front-matter values; values may be a string or array of
        // accepted strings). Sort by `order` ascending then by `slug`.
        // Render rows that look like the project-list block.
        const wrap = el('div', { class: 'b-project-list b-auto-list' });
        const placeholder = el('div', { class: 'b-md', html:
          '<p class="lede" style="opacity: 0.6">Loading…</p>' });
        wrap.appendChild(placeholder);
        loadAutoIndex().then(idx => {
          if (!wrap.isConnected) return;
          wrap.innerHTML = '';
          const matches = idx
            .filter(n => matchesFilter(n, b.filter || {}))
            .filter(n => !(b.exclude || []).includes(n.slug))
            .sort((a, c) => {
              if (a.order !== c.order) return a.order - c.order;
              return a.slug.localeCompare(c.slug);
            });
          if (matches.length === 0) {
            wrap.appendChild(el('div', { class: 'b-md', html:
              '<p style="opacity: 0.6">No notes match this filter yet.</p>' }));
            return;
          }
          matches.forEach((n, i) => {
            const row = el('div', { class: 'proj-row' });
            row.addEventListener('click', () => ctx.openNote(n.slug, ctx.depth));
            const num = b.numbered === false ? null
              : String(typeof n.order === 'number' && n.order < 99 ? n.order : i + 1).padStart(2, '0');
            if (num) row.appendChild(el('div', { class: 'n' }, num));
            const body = el('div', {});
            body.appendChild(el('div', { class: 'ttl' }, n.title || n.slug));
            // Tagline: only use the explicit `summary` field. The auto-extracted
            // `excerpt` stays in the index for other uses but we don't fall back
            // to it here — keeps the index visually clean.
            if (n.summary) body.appendChild(el('div', { class: 'tagline' }, n.summary));
            if (n.kicker) body.appendChild(el('div', { class: 'sub' }, n.kicker));
            row.appendChild(body);
            wrap.appendChild(row);
          });
        });
        return wrap;
      }
      case 'lede': return el('p', { class: 'b-lede' }, b.text);
      case 'p': return el('p', { class: 'b-p' }, b.text);
      case 'h2': return el('h2', { class: 'b-h2' }, [b.text]);
      case 'callout': return el('div', { class: 'b-callout' }, b.text);
      case 'callout-cta': {
        const wrap = el('div', { class: 'b-callout-cta' });
        wrap.appendChild(el('p', {}, b.text));
        if (b.email) {
          wrap.appendChild(el('a', { class: 'email', href: `mailto:${b.email}` }, b.email));
        }
        return wrap;
      }
      case 'shout': return el('div', { class: 'b-shout' }, b.text);
      case 'shout-quote': {
        const wrap = el('blockquote', { class: 'b-shout-quote' }, b.text);
        if (b.who) wrap.appendChild(el('span', { class: 'who' }, `— ${b.who}`));
        return wrap;
      }
      case 'tags': {
        const wrap = el('div', { class: 'b-tags' });
        for (const it of b.items) {
          wrap.appendChild(el('div', { class: 'tag-row' }, [
            el('span', { class: 't' }, it.tag),
            el('span', { class: 'x' }, it.text),
          ]));
        }
        return wrap;
      }
      case 'cards': {
        const wrap = el('div', { class: 'b-cards' });
        for (const it of b.items) {
          const klass = 'card-tile' + (it.href ? '' : ' is-static');
          const tile = el(it.href ? 'a' : 'div', { class: klass });
          if (it.href) {
            tile.addEventListener('click', (e) => { e.preventDefault(); ctx.openNote(it.href, ctx.depth); });
          }
          tile.appendChild(el('span', { class: 'lbl' }, it.label));
          if (it.sub) tile.appendChild(el('span', { class: 'sub' }, it.sub));
          wrap.appendChild(tile);
        }
        return wrap;
      }
      case 'principle': {
        const wrap = el('div', { class: 'b-principle' });
        wrap.appendChild(el('div', { class: 'num' }, b.n));
        const pbody = el('div', { class: 'pbody' });
        pbody.appendChild(el('h3', {}, b.title));
        pbody.appendChild(el('p', { class: 'ptext' }, b.text));
        if (b.example) pbody.appendChild(el('div', { class: 'pex' }, b.example));
        wrap.appendChild(pbody);
        return wrap;
      }
      case 'numbered': {
        const wrap = el('div', { class: 'b-numbered' });
        for (const it of b.items) {
          const row = el('div', { class: 'num-row' });
          row.appendChild(el('div', { class: 'n' }, it.n));
          const body = el('div', {});
          body.appendChild(el('div', { class: 'ttl' }, it.title));
          if (it.sub) body.appendChild(el('div', { class: 'sub' }, it.sub));
          row.appendChild(body);
          wrap.appendChild(row);
        }
        return wrap;
      }
      case 'timeline': {
        const wrap = el('div', { class: 'b-timeline' });
        for (const it of b.items) {
          wrap.appendChild(el('div', { class: 'tl-row' }, [
            el('div', { class: 'yr' }, it.year),
            el('div', { class: 'txt' }, it.text),
          ]));
        }
        return wrap;
      }
      case 'project-list': {
        const wrap = el('div', { class: 'b-project-list' });
        for (const it of b.items) {
          const row = el('div', { class: 'proj-row' });
          row.addEventListener('click', () => ctx.openNote(it.href, ctx.depth));
          row.appendChild(el('div', { class: 'n' }, it.n));
          const body = el('div', {});
          body.appendChild(el('div', { class: 'ttl' }, it.title));
          if (it.tagline) body.appendChild(el('div', { class: 'tagline' }, it.tagline));
          if (it.sub) body.appendChild(el('div', { class: 'sub' }, it.sub));
          row.appendChild(body);
          wrap.appendChild(row);
        }
        return wrap;
      }
      case 'tag-strip': {
        const wrap = el('div', { class: 'b-tag-strip' });
        for (const t of b.items) wrap.appendChild(el('span', { class: 'tag-chip' }, t));
        return wrap;
      }
      case 'links': {
        const wrap = el('div', { class: 'b-links' });
        for (const it of b.items) {
          const row = el('a', { class: 'link-row' }, it.label);
          if (it.href && it.href !== '#') {
            row.addEventListener('click', (e) => { e.preventDefault(); ctx.openNote(it.href, ctx.depth); });
          }
          wrap.appendChild(row);
        }
        return wrap;
      }
      case 'signers': {
        const wrap = el('div', { class: 'b-signers' });
        for (const s of b.items) wrap.appendChild(el('div', { class: 'signer' }, s));
        return wrap;
      }
      case 'addresses': {
        const wrap = el('div', { class: 'b-addresses' });
        for (const it of b.items) {
          const valueNode =
            typeof it.value === 'string' && /<\s*[a-z!/]/i.test(it.value)
              ? el('div', { class: 'val', html: it.value })
              : el('div', { class: 'val' }, it.value);
          wrap.appendChild(el('div', { class: 'addr-row' }, [
            el('div', { class: 'lbl' }, it.label),
            valueNode,
          ]));
        }
        wrap.querySelectorAll('a[data-note]').forEach(a => {
          a.addEventListener('click', (e) => {
            e.preventDefault();
            ctx.openNote(a.dataset.note, ctx.depth);
          });
        });
        return wrap;
      }
      default: return null;
    }
  }

  // ---------- note renderer ----------

  function renderPlaceholder(id, depth, isActive) {
    // Shown while content/<id>.md is loading, or if it doesn't exist.
    const note = el('section', {
      class: 'note ' + (isActive ? 'is-active' : 'is-spine'),
      'data-id': id,
      'data-accent': 'indigo',
    });
    if (!isActive) {
      const sh = el('div', { class: 'spine-head' });
      const closeBtn = el('button', { class: 'spine-close', 'aria-label': 'close note' }, '×');
      closeBtn.addEventListener('click', (e) => { e.stopPropagation(); app.closeOne(depth); });
      sh.appendChild(closeBtn);
      sh.appendChild(el('div', { class: 'spine-kicker' }, 'loading'));
      sh.appendChild(el('div', { class: 'spine-label' }, id));
      sh.appendChild(el('div', { class: 'spine-num' }, String(depth + 1).padStart(2, '0')));
      note.appendChild(sh);
      // Spine click is delegated on $stackInner.
      return note;
    }
    if (depth > 0) {
      const closeBtn = el('button', { class: 'note-close', 'aria-label': 'close' }, '×');
      closeBtn.addEventListener('click', () => app.closeOne(depth));
      note.appendChild(closeBtn);
    }
    const inner = el('div', { class: 'note-inner' });
    const head = el('div', { class: 'note-head' });
    head.appendChild(el('div', { class: 'note-kicker' }, MISSING.has(id) ? 'not found' : 'loading'));
    head.appendChild(el('h1', { class: 'note-title' }, MISSING.has(id) ? id : 'Loading…'));
    if (MISSING.has(id)) {
      const isFile = location.protocol === 'file:';
      const tip = isFile
        ? "This page was opened from a file:// URL. Browsers block fetch on file://, so the markdown notes can't be loaded. Run a local server (cd uzduz25 && python3 -m http.server 8080) and open http://localhost:8080 instead."
        : `Tried to load content/${id}.md but the request failed. Check the server is running from the uzduz25/ directory, and that the file exists. See the browser console for details.`;
      head.appendChild(el('p', { class: 'note-subtitle' }, tip));
    }
    inner.appendChild(head);
    note.appendChild(inner);
    return note;
  }

  // Slideshow: a sticky-right-column auto-advancing carousel of images for a
  // note. Images are stored at /assets/images/<slug>/<filename>; the note's
  // front matter declares the order via `images: [...]`. Auto-advances every
  // 5 s; pauses on hover; prev/next arrows; dot indicators below.
  function buildSlideshow(slug, images) {
    const wrap = el('div', { class: 'note-slideshow', 'data-slug': slug });
    const stage = el('div', { class: 'slideshow-stage' });
    const imgEls = images.map((name, i) => {
      const src = `assets/images/${slug}/${name}`;
      const im = el('img', {
        class: 'slideshow-img' + (i === 0 ? ' is-active' : ''),
        src,
        alt: '',
        loading: i === 0 ? 'eager' : 'lazy',
        decoding: 'async',
      });
      stage.appendChild(im);
      return im;
    });
    wrap.appendChild(stage);

    if (images.length > 1) {
      const prev = el('button', { class: 'slideshow-arrow prev', type: 'button', 'aria-label': 'previous image' }, '‹');
      const next = el('button', { class: 'slideshow-arrow next', type: 'button', 'aria-label': 'next image' }, '›');
      const dots = el('div', { class: 'slideshow-dots' });
      const dotEls = images.map((_, i) => {
        const d = el('button', {
          class: 'slideshow-dot' + (i === 0 ? ' is-active' : ''),
          type: 'button',
          'aria-label': `image ${i + 1}`,
          'data-i': String(i),
        });
        dots.appendChild(d);
        return d;
      });

      wrap.appendChild(prev);
      wrap.appendChild(next);
      wrap.appendChild(dots);

      let idx = 0;
      let timer = null;
      const setActive = (i) => {
        idx = (i + images.length) % images.length;
        imgEls.forEach((e, k) => e.classList.toggle('is-active', k === idx));
        dotEls.forEach((e, k) => e.classList.toggle('is-active', k === idx));
      };
      const advance = () => setActive(idx + 1);
      const start = () => { if (!timer) timer = setInterval(advance, 5000); };
      const stop = () => { if (timer) { clearInterval(timer); timer = null; } };

      prev.addEventListener('click', () => { setActive(idx - 1); stop(); start(); });
      next.addEventListener('click', () => { setActive(idx + 1); stop(); start(); });
      dotEls.forEach((d) => d.addEventListener('click', () => {
        setActive(parseInt(d.dataset.i, 10)); stop(); start();
      }));
      wrap.addEventListener('mouseenter', stop);
      wrap.addEventListener('mouseleave', start);
      // Cleanup when the note's column is removed from the DOM. Uses a
      // MutationObserver up the tree to detect detachment.
      const obs = new MutationObserver(() => {
        if (!wrap.isConnected) { stop(); obs.disconnect(); }
      });
      obs.observe(document.body, { childList: true, subtree: true });
      start();
    }

    return wrap;
  }

  function renderNote(id, depth, isActive) {
    const data = getNote(id);
    if (!data) return renderPlaceholder(id, depth, isActive);

    const note = el('section', {
      class: 'note ' + (isActive ? 'is-active' : 'is-spine'),
      'data-id': id,
      'data-accent': data.accent || 'indigo',
    });

    if (!isActive) {
      // Spine layout: rotated label + close button
      const spineHead = el('div', { class: 'spine-head' });
      const closeBtn = el('button', { class: 'spine-close', 'aria-label': 'close note' }, '×');
      closeBtn.addEventListener('click', (e) => { e.stopPropagation(); app.closeOne(depth); });
      spineHead.appendChild(closeBtn);

      const kicker = data.kicker || data.type || id;
      spineHead.appendChild(el('div', { class: 'spine-kicker' }, kicker));

      const labelText = (data.title || id).replace(/\*/g, '');
      spineHead.appendChild(el('div', { class: 'spine-label' }, labelText));

      spineHead.appendChild(el('div', { class: 'spine-num' }, String(depth + 1).padStart(2, '0')));

      note.appendChild(spineHead);
      // Click-to-activate is handled via delegation on $stackInner so it
      // survives in-place rebuilds.
      return note;
    }

    // ------ ACTIVE note (full content) ------

    note.appendChild(el('div', { class: 'note-depth' }));

    // close button (top right) — only shown on non-home active notes
    if (depth > 0) {
      const closeBtn = el('button', { class: 'note-close', 'aria-label': 'close' }, '×');
      closeBtn.addEventListener('click', () => app.closeOne(depth));
      note.appendChild(closeBtn);
    }

    const inner = el('div', { class: 'note-inner' });

    // ---- header ----
    const head = el('div', { class: 'note-head' });

    // homepage-only flourish
    if (id === 'home') {
      const flo = el('div', { class: 'cover-flourish' });
      flo.appendChild(el('div', { class: 'yr' }, 'EST. 2008 · REBOOTED 2020 · CLUJ-NAPOCA'));
      flo.appendChild(el('div', { class: 'stamp' }, ['a factory', el('br'), 'by the dozen']));
      head.appendChild(flo);
    } else {
      head.appendChild(el('div', { class: 'note-kicker' }, data.kicker || data.type));
    }

    head.appendChild(el('h1', { class: 'note-title' }, [emphasize(data.title)]));

    if (data.subtitle) {
      head.appendChild(el('p', { class: 'note-subtitle' }, data.subtitle));
    }

    if (data.pills && data.pills.length) {
      const pills = el('div', { class: 'note-pills' });
      for (const p of data.pills) {
        pills.appendChild(el('span', { class: 'note-pill' + (p.variant === 'on' ? ' on' : '') }, p.label));
      }
      head.appendChild(pills);
    }

    // For principle notes, place a prominent "next principle →" button in the
    // header. Loops back to principle 01 after the last one.
    if (data.type === 'principle' && AUTO_INDEX) {
      const principles = AUTO_INDEX
        .filter(n => n.type === 'principle')
        .sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
      const idx = principles.findIndex(n => n.slug === id);
      if (idx >= 0) {
        const next = principles[(idx + 1) % principles.length];
        const btn = el('a', {
          class: 'note-nav-next',
          href: `?n=${next.slug}`,
          'data-note': next.slug,
        }, [
          el('span', { class: 'lbl' }, `next: ${next.title}`),
          el('span', { class: 'arr' }, '→'),
        ]);
        btn.addEventListener('click', (e) => {
          e.preventDefault();
          app.openNoteAt(next.slug, depth);
        });
        head.appendChild(btn);
      }
    }

    inner.appendChild(head);

    // ---- body ----
    const body = el('div', { class: 'note-body' });
    const ctx = { depth, openNote: (target, fromDepth) => app.openNoteAt(target, fromDepth) };

    for (const block of data.body || []) {
      const node = renderBlock(block, ctx);
      if (node) body.appendChild(node);
    }

    inner.appendChild(body);

    // ---- footer micro ----
    const foot = el('div', { class: 'note-foot' }, [
      el('span', {}, `note · ${data.kicker || id}`),
      el('a', { href: '?n=contact', 'data-note': 'contact', class: 'note-foot-contact' }, 'contact'),
      el('span', {}, depth === 0 ? 'click any link to stack →' : `depth ${depth + 1}`),
    ]);
    foot.querySelectorAll('a[data-note]').forEach(a => {
      a.addEventListener('click', (e) => {
        e.preventDefault();
        app.openNoteAt(a.dataset.note, depth);
      });
    });
    inner.appendChild(foot);

    // The slideshow lives OUTSIDE the .note-inner max-width box so the body
    // keeps its full editorial width. Wraps inner + slideshow in a flex row.
    const hasSlideshow = Array.isArray(data.images) && data.images.length > 0;
    if (hasSlideshow) {
      const flex = el('div', { class: 'note-flex' });
      flex.appendChild(inner);
      flex.appendChild(buildSlideshow(id, data.images));
      note.appendChild(flex);
    } else {
      note.appendChild(inner);
    }

    return note;
  }

  // ---------- app ----------

  // Replace the contents of an existing .note element in place, preserving
  // its identity in the DOM so the CSS flex transition can animate the width
  // change between spine and active states.
  function rebuildNoteContent(noteEl, id, depth, isActive) {
    const fresh = renderNote(id, depth, isActive);
    if (!fresh) return;
    noteEl.className = fresh.className;
    Array.from(noteEl.attributes).forEach(a => {
      if (a.name === 'class' || a.name === 'style') return;
      noteEl.removeAttribute(a.name);
    });
    Array.from(fresh.attributes).forEach(a => {
      if (a.name === 'class' || a.name === 'style') return;
      noteEl.setAttribute(a.name, a.value);
    });
    noteEl.innerHTML = '';
    while (fresh.firstChild) noteEl.appendChild(fresh.firstChild);
  }

  const app = {
    stack: [],
    activeIndex: -1,
    _prevStack: [],

    render(opts) {
      const historyMode = (opts && opts.history) || 'push';
      // Keep activeIndex in range.
      if (this.activeIndex < 0 || this.activeIndex >= this.stack.length) {
        this.activeIndex = this.stack.length - 1;
      }

      const sameStack = arraysEqual(this.stack, this._prevStack);
      const isInitial = this._prevStack.length === 0;

      if (sameStack && !isInitial) {
        // Stack array is identical (only the active column changed). Rebuild
        // each .note in place; the flex-basis transition animates the width
        // change from spine (64px) to active (1fr) and vice versa.
        const noteEls = Array.from($stackInner.querySelectorAll('.note'));
        noteEls.forEach((noteEl, i) => {
          rebuildNoteContent(noteEl, this.stack[i], i, i === this.activeIndex);
        });
      } else {
        // Stack contents changed: full rebuild.
        $stackInner.innerHTML = '';
        this.stack.forEach((id, i) => {
          const node = renderNote(id, i, i === this.activeIndex);
          if (node) $stackInner.appendChild(node);
        });
      }
      // Mobile bookkeeping: every non-active note pins to the bottom of the
      // viewport via position:fixed with a per-spine `bottom` offset.
      // --spine-index = 0 for the bottom-most strip, growing upward.
      // --spine-count is set on stack-inner so the active note's height and
      // the page's bottom padding can subtract that band.
      const children = Array.from($stackInner.children);
      const spineEls = children.filter((_, i) => i !== this.activeIndex);
      const spineCount = spineEls.length;
      $stackInner.style.setProperty('--spine-count', String(spineCount));
      spineEls.forEach((noteEl, j) => {
        // The last spine in DOM order pins to the bottom (--spine-index=0);
        // earlier spines stack above it.
        noteEl.style.setProperty('--spine-index', String(spineCount - 1 - j));
      });
      this._prevStack = this.stack.slice();

      this.renderChromeNav();
      if (historyMode !== 'none') setStackUrl(this.stack, this.activeIndex, historyMode);
      // Trigger async loads for any unresolved ids; re-render without writing
      // history again when they arrive.
      this.stack.forEach(id => {
        if (!getNote(id) && !MISSING.has(id)) {
          loadNote(id).then(() => this.render({ history: 'none' }));
        }
      });
    },

    renderChromeNav() {
      $chromeNav.innerHTML = '';
      if ($mobileMenu) $mobileMenu.innerHTML = '';
      // Only the currently-active column marks its tab as active.
      const activeId = this.stack[this.activeIndex];
      const goToTab = (t) => {
        // If the page is already in the stack, just promote it to active
        // (no duplicate column). The flex transition slides its column from
        // spine width (64px) to fill, and the previously-active column
        // shrinks to a spine in place.
        const existing = this.stack.indexOf(t.id);
        if (existing !== -1) {
          if (existing !== this.activeIndex) {
            this.activeIndex = existing;
            this.render();
            scrollActiveIntoViewOnMobile();
          }
          return;
        }
        // Otherwise: replace the stack with this tab as the only column.
        this.stack = [t.id];
        this.activeIndex = 0;
        this.render();
        scrollActiveIntoViewOnMobile();
      };
      for (const t of PRIMARY_TABS) {
        const btn = el('button', {
          class: t.id === activeId ? 'is-active' : '',
        }, t.label);
        btn.addEventListener('click', () => goToTab(t));
        $chromeNav.appendChild(btn);

        if ($mobileMenu) {
          const mobileBtn = el('button', {
            class: 'mobile-menu-item' + (t.id === activeId ? ' is-active' : ''),
          }, [
            solarIcon(t.icon),
            el('span', {}, t.label),
          ]);
          mobileBtn.addEventListener('click', () => {
            closeMobileMenu();
            goToTab(t);
          });
          $mobileMenu.appendChild(mobileBtn);
        }
      }
    },

    // Open a note triggered from a link inside the column at fromDepth.
    // If the target is already somewhere in the stack, just promote it to
    // active (no duplicate). Otherwise, push it after fromDepth.
    openNoteAt(targetId, fromDepth) {
      const existing = this.stack.indexOf(targetId);
      if (existing !== -1) {
        if (existing !== this.activeIndex) {
          this.activeIndex = existing;
          this.render();
          scrollActiveIntoViewOnMobile();
        }
        return;
      }
      // Truncate to fromDepth + 1 so the new note replaces anything that was
      // to the right of the column the user clicked from.
      this.stack = this.stack.slice(0, fromDepth + 1);
      this.stack.push(targetId);
      this.activeIndex = this.stack.length - 1;
      this.render();
      scrollActiveIntoViewOnMobile();
    },

    // Click on a spine (any column that isn't currently active): make it the
    // active column. The previously-active column collapses to a spine and
    // stays in the stack at its original position. Nothing is dropped.
    activateAt(depth) {
      if (depth < 0 || depth >= this.stack.length) return;
      if (depth === this.activeIndex) return;
      this.activeIndex = depth;
      this.render();
      scrollActiveIntoViewOnMobile();
    },

    // Close × on any column (active or spine): remove just that one column
    // and adjust activeIndex. The other columns keep their positions.
    closeOne(depth) {
      if (depth < 0 || depth >= this.stack.length) return;
      this.stack.splice(depth, 1);
      if (this.stack.length === 0) {
        this.stack = ['home'];
        this.activeIndex = 0;
      } else {
        if (depth < this.activeIndex) this.activeIndex--;
        else if (depth === this.activeIndex) this.activeIndex = Math.min(depth, this.stack.length - 1);
        if (this.activeIndex >= this.stack.length) this.activeIndex = this.stack.length - 1;
        if (this.activeIndex < 0) this.activeIndex = 0;
      }
      this.render();
    },
  };

  function closeMobileMenu() {
    if (!$mobileMenu || !$mobileMenuToggle) return;
    $mobileMenu.hidden = true;
    $mobileMenuToggle.setAttribute('aria-expanded', 'false');
    $mobileMenuToggle.setAttribute('aria-label', 'open menu');
  }

  function openMobileMenu() {
    if (!$mobileMenu || !$mobileMenuToggle) return;
    $mobileMenu.hidden = false;
    $mobileMenuToggle.setAttribute('aria-expanded', 'true');
    $mobileMenuToggle.setAttribute('aria-label', 'close menu');
  }

  function toggleMobileMenu() {
    if (!$mobileMenu || !$mobileMenuToggle) return;
    if ($mobileMenu.hidden) openMobileMenu();
    else closeMobileMenu();
  }

  if ($mobileMenuToggle && $mobileMenu) {
    closeMobileMenu();
    $mobileMenuToggle.addEventListener('click', (e) => {
      e.stopPropagation();
      toggleMobileMenu();
    });
    $mobileMenu.addEventListener('click', (e) => e.stopPropagation());
    document.addEventListener('click', () => closeMobileMenu());
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') closeMobileMenu();
    });
    window.addEventListener('resize', () => {
      if (!window.matchMedia || !window.matchMedia('(max-width: 720px)').matches) {
        closeMobileMenu();
      }
    });
  }

  // Delegated handler for spine clicks. Survives in-place rebuilds, since
  // rebuildNoteContent recreates child elements but keeps the .note wrapper.
  $stackInner.addEventListener('click', (e) => {
    const sp = e.target.closest('.note.is-spine');
    if (!sp || !$stackInner.contains(sp)) return;
    // The spine × button has its own listener; ignore clicks on it.
    if (e.target.closest('.spine-close')) return;
    const depth = Array.from($stackInner.children).indexOf(sp);
    if (depth >= 0) app.activateAt(depth);
  });

  // brand link → reset to home (or just refocus home if it's in the stack).
  document.querySelector('.brand').addEventListener('click', () => {
    const existing = app.stack.indexOf('home');
    if (existing !== -1) {
      if (existing !== app.activeIndex) { app.activeIndex = existing; app.render(); }
      return;
    }
    app.stack = ['home'];
    app.activeIndex = 0;
    app.render();
  });

  // boot — replace, not push (no duplicate first entry).
  {
    const init = getStackFromUrl();
    app.stack = init.stack;
    app.activeIndex = init.activeIndex;
    app.render({ history: 'replace' });
  }

  // Browser back/forward: read the URL the browser already restored, render
  // with no history write (URL is already correct).
  window.addEventListener('popstate', () => {
    const next = getStackFromUrl();
    app.stack = next.stack;
    app.activeIndex = next.activeIndex;
    app.render({ history: 'none' });
  });

  // ---------- WebMCP (browser-side agent tool surface) ----------
  // Expose a tiny set of tools to AI agents browsing the page, per the W3C
  // WebMCP draft. The intent is discoverability, not site control: tools
  // are read-only and call the same fetches a browser would make anyway.
  // Spec: https://webmachinelearning.github.io/webmcp/
  if (typeof navigator !== 'undefined' && navigator.modelContext &&
      typeof navigator.modelContext.provideContext === 'function') {
    try {
      navigator.modelContext.provideContext({
        tools: [
          {
            name: 'list_notes',
            description: 'Return the index of every published note on uzinaduzina.org with type, title, summary, and slug.',
            inputSchema: { type: 'object', properties: {}, additionalProperties: false },
            execute: async () => {
              const idx = await loadAutoIndex();
              return { notes: idx };
            },
          },
          {
            name: 'fetch_note_markdown',
            description: 'Fetch the original Markdown source for a single note by slug (e.g. "project-democraicy", "manifesto-living-heritage", "team-liviu-pop"). Returns front matter + body verbatim.',
            inputSchema: {
              type: 'object',
              properties: {
                slug: { type: 'string', description: 'Note slug, no .md extension. See list_notes for available slugs.' },
              },
              required: ['slug'],
              additionalProperties: false,
            },
            execute: async ({ slug }) => {
              if (typeof slug !== 'string' || !/^[\w-]+$/.test(slug)) {
                return { error: 'invalid slug' };
              }
              const r = await fetch(`content/${slug}.md`, { cache: 'no-cache' });
              if (!r.ok) return { error: `not found (HTTP ${r.status})` };
              return { slug, markdown: await r.text() };
            },
          },
          {
            name: 'open_note_stack',
            description: 'Open one or more notes in the user-visible stacked-notes UI. Useful when guiding a human reader to a particular page.',
            inputSchema: {
              type: 'object',
              properties: {
                slugs: { type: 'array', items: { type: 'string' }, minItems: 1, maxItems: 6,
                  description: 'Ordered slugs to push onto the stack, left-to-right. Last one becomes the active column.' },
              },
              required: ['slugs'],
              additionalProperties: false,
            },
            execute: async ({ slugs }) => {
              if (!Array.isArray(slugs) || slugs.length === 0) return { error: 'no slugs' };
              const clean = slugs.filter(s => typeof s === 'string' && /^[\w-]+$/.test(s)).slice(0, 6);
              if (!clean.length) return { error: 'no valid slugs' };
              app.stack = clean;
              app.activeIndex = clean.length - 1;
              app.render();
              return { opened: clean, activeIndex: clean.length - 1 };
            },
          },
        ],
      });
    } catch (e) {
      // WebMCP not actually available or rejected; ignore silently.
    }
  }
})();
